version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile.prod
    container_name: go-app
    ports:
      - 8080:8080
    environment:
      - ENV=${ENV}
      - SECRET_KEY=${SECRET_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SSL_MODE=${SSL_MODE}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - IMAGE_KIT_PUBLIC_KEY=${IMAGE_KIT_PUBLIC_KEY}
      - IMAGE_KIT_PRIVATE_KEY=${IMAGE_KIT_PRIVATE_KEY}
      - IMAGE_KIT_URL_ENDPOINT=${IMAGE_KIT_URL_ENDPOINT}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
