version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile.prod
    container_name: go-app
    ports:
      - 8080:8080
    environment:
      - ENV=${ENV}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SSL_MODE=${SSL_MODE}