version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile.dev
    container_name: go-app
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    environment:
      - ENV=${ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SSL_MODE=${SSL_MODE}
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
