services:
  - type: web
    name: go-app
    env: docker
    plan: free
    dockerfilePath: ./docker/go/Dockerfile.prod
    healthCheckPath: /
    regions: oregon
    autoDeploy: true
    buildCommand: ""
    startCommand: "./main"
    envVars:
      - key: DB_HOST
        valueFromInstance: DB_HOST
      - key: DB_PORT
        valueFromInstance: DB_PORT
      - key: DB_NAME
        valueFromInstance: DB_NAME
      - key: DB_USER
        valueFromInstance: DB_USER
      - key: DB_PASSWORD
        valueFromInstance: DB_PASSWORD
      - key: SSL_MODE
        valueFromInstance: SSL_MODE

databases:
  - name: go-app-db
    plan: free
    postgresVersion: 15
    envVars:
      - key: POSTGRES_USER
        valueFromInstance: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        valueFromInstance: POSTGRES_PASSWORD
      - key: POSTGRES_DB
        valueFromInstance: POSTGRES_DB