// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/emailVerification": {
            "get": {
                "description": "リクエストからメールアドレス取得後、tokenTypeに応じてチェックし、メールアドレス宛にtokenを含めた画面URLをメールで送信",
                "tags": [
                    "auth"
                ],
                "summary": "メールアドレスの本人確認",
                "parameters": [
                    {
                        "type": "string",
                        "description": "メールアドレス",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "トークンタイプ register or reset",
                        "name": "tokenType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "メールアドレスとパスワードが合致したら、jwtトークンをクライアントに返却",
                "tags": [
                    "auth"
                ],
                "summary": "ログイン",
                "parameters": [
                    {
                        "description": "ログイン情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-auth_LoginResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "メールアドレス確認後にリクエスト内容をユーザーテーブルに保存",
                "tags": [
                    "auth"
                ],
                "summary": "ユーザー登録",
                "parameters": [
                    {
                        "description": "ユーザー情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/resetPass": {
            "put": {
                "description": "メール内リンクで本人確認後、トークンと新しいパスワードをリクエストで取得し、パスワードを更新する",
                "tags": [
                    "auth"
                ],
                "summary": "ログアウト状態からパスワードを変更",
                "parameters": [
                    {
                        "description": "tokenと新しいパスワード",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ResetPassRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/updatePass/{userId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "現在のパスワードと新しいパスワードをリクエストで取得し、現在のパスワードが合致したら、新しいパスワードに更新する",
                "tags": [
                    "auth"
                ],
                "summary": "ログイン状態からパスワードを変更",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "メールアドレス",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UpdatePassRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/expedition/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "遠征、出費、試合、訪れた施設の情報を保存する。fileIdはimagekitのfileIdで、ユニークな値です。",
                "tags": [
                    "expedition"
                ],
                "summary": "遠征記録を作成",
                "parameters": [
                    {
                        "description": "遠征記録作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/expedition.CreateExpeditionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/expedition/delete/{expeditionId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "遠征記録とそれに関連する全てのデータ（画像、いいね、支払い、試合情報など）を削除する",
                "tags": [
                    "expedition"
                ],
                "summary": "遠征記録を削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "遠征記録ID",
                        "name": "expeditionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "遠征記録が見つかりません",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/expedition/like/{expeditionId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ユーザーが遠征記録にいいねを付ける",
                "tags": [
                    "expedition"
                ],
                "summary": "遠征記録にいいねする",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "遠征記録ID",
                        "name": "expeditionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "遠征記録が見つかりません",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/expedition/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ページネーション付きで遠征記録一覧を取得します\u003cbr\u003eteamIdとsportIdを指定すると、そのチーム、スポーツの遠征記録一覧を取得します。指定しなければ全ての遠征記録一覧を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expedition"
                ],
                "summary": "遠征記録一覧を取得",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "ページ番号",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "スポーツID",
                        "name": "sportId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "チームID",
                        "name": "teamId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-array_expedition_ExpeditionListResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "遠征記録が見つかりません",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/expedition/unlike/{expeditionId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ユーザーが遠征記録のいいねを外す",
                "tags": [
                    "expedition"
                ],
                "summary": "遠征記録のいいねを外す",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "遠征記録ID",
                        "name": "expeditionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "いいねが見つかりません",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/expedition/update/{expeditionId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "遠征、出費、試合、訪れた施設の情報を更新する。\u003cbr\u003ePayment, VisitedFacility, Game, GameScoreのdeleteにはidの配列ですが、ExpeditionImageのdeleteにはfileId(string)の配列をリクエストで渡してください",
                "tags": [
                    "expedition"
                ],
                "summary": "遠征記録を更新",
                "parameters": [
                    {
                        "description": "遠征記録更新リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/expedition.UpdateExpeditionRequestBody"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "遠征記録ID",
                        "name": "expeditionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "ユーザーが見つかりません",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/expedition/{expeditionId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "遠征記録詳細情報を取得",
                "tags": [
                    "expedition"
                ],
                "summary": "idから遠征記録詳細を取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "expeditionId",
                        "name": "expeditionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-expedition_GetExpeditionDetailResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "403": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/league/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストボディに削除対象のIDを指定してリーグ情報を削除します",
                "tags": [
                    "league"
                ],
                "summary": "リーグ削除",
                "parameters": [
                    {
                        "description": "リーグID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/league/leagueAdd": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストからリーグ情報を取得後、重複確認を行い登録する。",
                "tags": [
                    "league"
                ],
                "summary": "リーグの追加",
                "parameters": [
                    {
                        "description": "リーグ情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.LeagueAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/league/leagues": {
            "get": {
                "description": "リーグ情報のレコードを全件取得して、一覧として表示する。",
                "tags": [
                    "league"
                ],
                "summary": "リーグ全件検索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "キーワード",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/league/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストボディに更新対象のIDを指定してリーグ情報を更新します",
                "tags": [
                    "league"
                ],
                "summary": "リーグ更新",
                "parameters": [
                    {
                        "description": "リーグ情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.LeagueUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/sample/helloWorld": {
            "get": {
                "tags": [
                    "sample"
                ],
                "summary": "サンプルAPI",
                "responses": {}
            }
        },
        "/api/sample/protectedHelloWorld": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "sample"
                ],
                "summary": "サンプルAPI",
                "responses": {}
            }
        },
        "/api/sports/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストボディに削除対象のIDを指定してスポーツ情報を削除します",
                "tags": [
                    "sports"
                ],
                "summary": "スポーツ削除",
                "parameters": [
                    {
                        "description": "スポーツ情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/sports/sports": {
            "get": {
                "description": "スポーツ情報のレコードを全件取得して、一覧として表示する。",
                "tags": [
                    "sports"
                ],
                "summary": "スポーツ全件検索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "キーワード",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/sports/sportsAdd": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストからスポーツ情報を取得後、重複確認を行い登録する。",
                "tags": [
                    "sports"
                ],
                "summary": "スポーツの追加",
                "parameters": [
                    {
                        "description": "スポーツ情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.SportsAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/sports/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストボディに更新対象のIDを指定してスポーツ情報を更新します",
                "tags": [
                    "sports"
                ],
                "summary": "スポーツ更新",
                "parameters": [
                    {
                        "description": "スポーツ情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.SportsUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/stadium/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストボディに削除対象のIDを指定してスタジアムを削除します",
                "tags": [
                    "stadium"
                ],
                "summary": "スタジアム削除",
                "parameters": [
                    {
                        "description": "スタジアムID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/stadium/stadiumAdd": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストからスタジアム情報を追加後、重複確認を行い登録する。",
                "tags": [
                    "stadium"
                ],
                "summary": "スタジアム追加",
                "parameters": [
                    {
                        "description": "スタジアム情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.StadiumAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/stadium/stadiums": {
            "get": {
                "description": "スタジアム情報のレコードを全件取得して、一覧として表示する。",
                "tags": [
                    "stadium"
                ],
                "summary": "スタジアム全件検索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "キーワード",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/stadium/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストボディに更新対象のIDを指定してスタジアムを更新します",
                "tags": [
                    "stadium"
                ],
                "summary": "スタジアム更新",
                "parameters": [
                    {
                        "description": "スタジアム情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.StadiumUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/team/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストボディに削除対象のIDを指定してチーム情報を削除します",
                "tags": [
                    "team"
                ],
                "summary": "チーム削除",
                "parameters": [
                    {
                        "description": "チームID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/team/teamAdd": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストからチーム情報を取得後、重複確認を行い登録する。",
                "tags": [
                    "team"
                ],
                "summary": "チームの追加",
                "parameters": [
                    {
                        "description": "チーム情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.TeamAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/team/teams": {
            "get": {
                "description": "チーム情報のレコードを全件取得して、一覧として表示する。",
                "tags": [
                    "team"
                ],
                "summary": "チーム全件検索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "キーワード",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/team/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "リクエストボディに更新対象のIDを指定してチーム情報を更新します",
                "tags": [
                    "team"
                ],
                "summary": "チーム情報更新",
                "parameters": [
                    {
                        "description": "チーム情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/adminTool.TeamUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessBasicResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/upload/images": {
            "post": {
                "description": "画像をアップロードし、URLを返します。\u003cbr\u003eプロフィール、スタジアム、遠征など、格納フォルダを指定してください。\u003cbr\u003e画像は1枚から10枚アップロードできるが、Swagger UIでは1つしか選択できません。\u003cbr\u003eファイルの拡張子は、[\".jpg\", \".jpeg\", \".png\"]だけを受け付けています。ファイルサイズは最大5MBを上限としています。",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "画像をクラウドストレージ(imagekit)にアップロード",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格納フォルダ",
                        "name": "folder",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "画像ファイル",
                        "name": "images",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-upload_UploadImagesResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/user/isUnique/{username}": {
            "get": {
                "description": "リクエストと同じuserNameが登録済みかチェックする",
                "tags": [
                    "user"
                ],
                "summary": "ユーザーネームの重複チェック",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "一意かのフラグ",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-user_IsUniqueUsernameResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/user/logined": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ヘッダーのトークンからユーザーを取得する",
                "tags": [
                    "user"
                ],
                "summary": "ログイン済みの場合、ログインユーザーの情報を取得",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-user_UserResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/user/update/{userId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "userIdが同じユーザーの情報を変更する",
                "tags": [
                    "user"
                ],
                "summary": "ユーザー情報変更",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "userId",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateUserRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ユーザー情報",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-user_UserResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/user/userId/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "userIdからユーザーを1人取得",
                "tags": [
                    "user"
                ],
                "summary": "userIdからユーザー情報取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ユーザー情報",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-user_UserResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        },
        "/api/user/username/{username}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "usernameからユーザーを1人取得",
                "tags": [
                    "user"
                ],
                "summary": "usernameからユーザー情報取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ユーザー情報",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse-user_UserResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "404": {
                        "description": "not foundエラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    },
                    "500": {
                        "description": "内部エラー",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorBasicResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "adminTool.DeleteRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "adminTool.LeagueAddRequest": {
            "type": "object",
            "required": [
                "sport_id"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "sport_id": {
                    "type": "integer"
                }
            }
        },
        "adminTool.LeagueUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "sport_id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sport_id": {
                    "type": "integer"
                }
            }
        },
        "adminTool.SportsAddRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "adminTool.SportsUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "adminTool.StadiumAddRequest": {
            "type": "object",
            "required": [
                "address",
                "capacity",
                "description",
                "image",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "adminTool.StadiumUpdateRequest": {
            "type": "object",
            "required": [
                "address",
                "capacity",
                "description",
                "id",
                "image",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "adminTool.TeamAddRequest": {
            "type": "object",
            "required": [
                "LeagueId",
                "name",
                "sportsId",
                "stadiumId"
            ],
            "properties": {
                "LeagueId": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sportsId": {
                    "type": "integer"
                },
                "stadiumId": {
                    "type": "integer"
                }
            }
        },
        "adminTool.TeamUpdateRequest": {
            "type": "object",
            "required": [
                "LeagueId",
                "name",
                "sportsId",
                "stadiumId",
                "teamId"
            ],
            "properties": {
                "LeagueId": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sportsId": {
                    "type": "integer"
                },
                "stadiumId": {
                    "type": "integer"
                },
                "teamId": {
                    "type": "integer"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "tanaka@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6,
                    "example": "password123"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "1234567890"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "token",
                "username"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "野球が好きです！"
                },
                "fileId": {
                    "type": "string",
                    "example": "1234567890"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "tanaka taro"
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6,
                    "example": "password123"
                },
                "profileImage": {
                    "type": "string",
                    "example": "https://ik.imagekit.io/your_imagekit_id/image.jpg"
                },
                "token": {
                    "type": "string",
                    "example": "1234567890"
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "user123"
                }
            }
        },
        "auth.ResetPassRequest": {
            "type": "object",
            "required": [
                "afterPassword",
                "token"
            ],
            "properties": {
                "afterPassword": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6,
                    "example": "password456"
                },
                "token": {
                    "type": "string",
                    "example": "1234567890"
                }
            }
        },
        "auth.UpdatePassRequestBody": {
            "type": "object",
            "required": [
                "afterPassword",
                "beforePassword"
            ],
            "properties": {
                "afterPassword": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6,
                    "example": "password456"
                },
                "beforePassword": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6,
                    "example": "password123"
                }
            }
        },
        "expedition.CreateExpeditionRequest": {
            "type": "object",
            "required": [
                "endDate",
                "games",
                "isPublic",
                "memo",
                "payments",
                "sportId",
                "stadiumId",
                "startDate",
                "title",
                "visitedFacilities"
            ],
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.GameRequest"
                    }
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.ExpeditionImageRequest"
                    }
                },
                "isPublic": {
                    "type": "boolean"
                },
                "memo": {
                    "type": "string"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.PaymentRequest"
                    }
                },
                "sportId": {
                    "type": "integer"
                },
                "stadiumId": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "visitedFacilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.VisitedFacilityRequest"
                    }
                }
            }
        },
        "expedition.ExpeditionImageRequest": {
            "type": "object",
            "required": [
                "fileId",
                "image"
            ],
            "properties": {
                "fileId": {
                    "type": "string",
                    "example": "file_1234567890"
                },
                "image": {
                    "type": "string",
                    "example": "https://ik.imagekit.io/your_imagekit_id/image.jpg"
                }
            }
        },
        "expedition.ExpeditionImageResponse": {
            "type": "object",
            "properties": {
                "fileId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                }
            }
        },
        "expedition.ExpeditionListResponse": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://ik.imagekit.io/your_imagekit_id/image.jpg"
                    ]
                },
                "likesCount": {
                    "type": "integer",
                    "example": 10
                },
                "sportId": {
                    "type": "integer",
                    "example": 1
                },
                "sportName": {
                    "type": "string",
                    "example": "野球"
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "team1Name": {
                    "type": "string",
                    "example": "ヤクルト"
                },
                "team2Name": {
                    "type": "string",
                    "example": "ソフトバンク"
                },
                "title": {
                    "type": "string",
                    "example": "野球観戦の遠征記録"
                },
                "userIcon": {
                    "type": "string",
                    "example": "https://ik.imagekit.io/your_imagekit_id/image.jpg"
                },
                "userId": {
                    "type": "integer",
                    "example": 1
                },
                "userName": {
                    "type": "string",
                    "example": "ユーザー名"
                }
            }
        },
        "expedition.GameRequest": {
            "type": "object",
            "required": [
                "comment",
                "date",
                "scores",
                "team1Id",
                "team2Id"
            ],
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "熱い試合でした！！"
                },
                "date": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.GameScoreRequest"
                    }
                },
                "team1Id": {
                    "type": "integer",
                    "example": 1
                },
                "team2Id": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "expedition.GameResponse": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.GameScoreResponse"
                    }
                },
                "team1Id": {
                    "type": "integer"
                },
                "team2Id": {
                    "type": "integer"
                }
            }
        },
        "expedition.GameScoreRequest": {
            "type": "object",
            "required": [
                "order",
                "score",
                "teamId"
            ],
            "properties": {
                "order": {
                    "type": "integer",
                    "example": 1
                },
                "score": {
                    "type": "integer",
                    "example": 1
                },
                "teamId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "expedition.GameScoreResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "order": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "teamId": {
                    "type": "integer"
                }
            }
        },
        "expedition.GetExpeditionDetailResponse": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "expeditionImages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.ExpeditionImageResponse"
                    }
                },
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.GameResponse"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "memo": {
                    "type": "string"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.PaymentResponse"
                    }
                },
                "sportId": {
                    "type": "integer"
                },
                "stadiumId": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "visitedFacilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.VisitedFacilityResponse"
                    }
                }
            }
        },
        "expedition.PaymentRequest": {
            "type": "object",
            "required": [
                "cost",
                "date",
                "title"
            ],
            "properties": {
                "cost": {
                    "type": "integer",
                    "example": 5000
                },
                "date": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "チケット代"
                }
            }
        },
        "expedition.PaymentResponse": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "expedition.UpdateExpeditionImagesRequest": {
            "type": "object",
            "properties": {
                "add": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.ExpeditionImageRequest"
                    }
                },
                "delete": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "expedition.UpdateExpeditionRequestBody": {
            "type": "object",
            "required": [
                "endDate",
                "games",
                "images",
                "memo",
                "payments",
                "sportId",
                "stadiumId",
                "startDate",
                "title",
                "visitedFacilities"
            ],
            "properties": {
                "endDate": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "games": {
                    "$ref": "#/definitions/expedition.UpdateGamesRequest"
                },
                "images": {
                    "$ref": "#/definitions/expedition.UpdateExpeditionImagesRequest"
                },
                "isPublic": {
                    "type": "boolean",
                    "example": true
                },
                "memo": {
                    "type": "string",
                    "example": "初めてのスタジアム訪問。とても楽しかった！"
                },
                "payments": {
                    "$ref": "#/definitions/expedition.UpdatePaymentsRequest"
                },
                "sportId": {
                    "type": "integer",
                    "example": 1
                },
                "stadiumId": {
                    "type": "integer",
                    "example": 1
                },
                "startDate": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "野球観戦の遠征記録"
                },
                "visitedFacilities": {
                    "$ref": "#/definitions/expedition.UpdateVisitedFacilitiesRequest"
                }
            }
        },
        "expedition.UpdateGameRequest": {
            "type": "object",
            "required": [
                "comment",
                "date",
                "id",
                "scores",
                "team1Id",
                "team2Id"
            ],
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "熱い試合でした！！"
                },
                "date": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "scores": {
                    "$ref": "#/definitions/expedition.UpdateGameScoresRequest"
                },
                "team1Id": {
                    "type": "integer",
                    "example": 1
                },
                "team2Id": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "expedition.UpdateGameScoreRequest": {
            "type": "object",
            "required": [
                "id",
                "order",
                "score",
                "teamId"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "order": {
                    "type": "integer",
                    "example": 1
                },
                "score": {
                    "type": "integer",
                    "example": 1
                },
                "teamId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "expedition.UpdateGameScoresRequest": {
            "type": "object",
            "properties": {
                "add": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.GameScoreRequest"
                    }
                },
                "delete": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "update": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.UpdateGameScoreRequest"
                    }
                }
            }
        },
        "expedition.UpdateGamesRequest": {
            "type": "object",
            "properties": {
                "add": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.GameRequest"
                    }
                },
                "delete": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "update": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.UpdateGameRequest"
                    }
                }
            }
        },
        "expedition.UpdatePaymentRequest": {
            "type": "object",
            "required": [
                "cost",
                "date",
                "id",
                "title"
            ],
            "properties": {
                "cost": {
                    "type": "integer",
                    "example": 5000
                },
                "date": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "チケット代"
                }
            }
        },
        "expedition.UpdatePaymentsRequest": {
            "type": "object",
            "properties": {
                "add": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.PaymentRequest"
                    }
                },
                "delete": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "update": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.UpdatePaymentRequest"
                    }
                }
            }
        },
        "expedition.UpdateVisitedFacilitiesRequest": {
            "type": "object",
            "properties": {
                "add": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.VisitedFacilityRequest"
                    }
                },
                "delete": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "update": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.UpdateVisitedFacilityRequest"
                    }
                }
            }
        },
        "expedition.UpdateVisitedFacilityRequest": {
            "type": "object",
            "required": [
                "address",
                "color",
                "icon",
                "id",
                "latitude",
                "longitude",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "東京都千代田区丸の内1-1-1"
                },
                "color": {
                    "type": "string",
                    "example": "#00FF00"
                },
                "icon": {
                    "type": "string",
                    "example": "train"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "latitude": {
                    "type": "number",
                    "example": 35.6812
                },
                "longitude": {
                    "type": "number",
                    "example": 139.7671
                },
                "name": {
                    "type": "string",
                    "example": "東京駅"
                }
            }
        },
        "expedition.VisitedFacilityRequest": {
            "type": "object",
            "required": [
                "address",
                "color",
                "icon",
                "latitude",
                "longitude",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "東京都千代田区丸の内1-1-1"
                },
                "color": {
                    "type": "string",
                    "example": "#00FF00"
                },
                "icon": {
                    "type": "string",
                    "example": "train"
                },
                "latitude": {
                    "type": "number",
                    "example": 35.6812
                },
                "longitude": {
                    "type": "number",
                    "example": 139.7671
                },
                "name": {
                    "type": "string",
                    "example": "東京駅"
                }
            }
        },
        "expedition.VisitedFacilityResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "upload.UploadImagesResponse": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/upload.UploadToImageKitResponse"
                    }
                }
            }
        },
        "upload.UploadToImageKitResponse": {
            "type": "object",
            "properties": {
                "fileId": {
                    "type": "string",
                    "example": "file_1234567890"
                },
                "url": {
                    "type": "string",
                    "example": "https://ik.imagekit.io/your_imagekit_id/image.jpg"
                }
            }
        },
        "user.IsUniqueUsernameResponse": {
            "type": "object",
            "properties": {
                "isUnique": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "user.UpdateUserRequestBody": {
            "type": "object",
            "required": [
                "description",
                "name",
                "profileImage"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "野球が好きです！"
                },
                "fileId": {
                    "type": "string",
                    "example": "1234567890"
                },
                "name": {
                    "type": "string",
                    "example": "tanaka taro"
                },
                "profileImage": {
                    "type": "string",
                    "example": "https://ik.imagekit.io/your_imagekit_id/image.jpg"
                }
            }
        },
        "user.UserResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "野球が好きです！"
                },
                "email": {
                    "type": "string",
                    "example": "tanaka@example.com"
                },
                "fileId": {
                    "type": "string",
                    "example": "1234567890"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "tanaka taro"
                },
                "profileImage": {
                    "type": "string",
                    "example": "https://ik.imagekit.io/your_imagekit_id/image.jpg"
                },
                "username": {
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "utils.ApiResponse-array_expedition_ExpeditionListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/expedition.ExpeditionListResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "成功しました！！"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.ApiResponse-auth_LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.LoginResponse"
                },
                "message": {
                    "type": "string",
                    "example": "成功しました！！"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.ApiResponse-expedition_GetExpeditionDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/expedition.GetExpeditionDetailResponse"
                },
                "message": {
                    "type": "string",
                    "example": "成功しました！！"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.ApiResponse-upload_UploadImagesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/upload.UploadImagesResponse"
                },
                "message": {
                    "type": "string",
                    "example": "成功しました！！"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.ApiResponse-user_IsUniqueUsernameResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.IsUniqueUsernameResponse"
                },
                "message": {
                    "type": "string",
                    "example": "成功しました！！"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.ApiResponse-user_UserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.UserResponse"
                },
                "message": {
                    "type": "string",
                    "example": "成功しました！！"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.ErrorBasicResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "エラーメッセージ"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "utils.SuccessBasicResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "成功しました！！"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ビジターゴーAPI",
	Description:      "このapiは、ビジターゴーのAPIで、ユーザー、スタジアム、遠征記録、などについて扱います。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
